name: "Continuous Integration"

on:
    push:
        tags:
            - "*.*"
jobs:
    build-frontend:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '18.x'
            
            - name: Install dependencies
              run: | 
                cd frontends
                npm install

            - name: Build Frontend
              run: |
                cd frontends
                npm run build

            - name: Upload build artifact
              uses: actions/upload-artifact@v3
              with:
                name: frontend-build
                path: app/static

    build-and-push-docker:
        needs: build-frontend
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Download build artifact
              uses: actions/download-artifact@v3
              with:
                    name: frontend-build
                    path: app/static

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
                    
            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.TOKEN }}

            - name: Build Docker Image
              uses: docker/build-push-action@v4
              with:
                context: .
                file: Dockerfile
                push: true
                tags: ghcr.io/carelessdev/prometheuzdy-web:latest,ghcr.io/carelessdev/prometheuzdy-web:${{ github.ref_name }}
                platforms: linux/amd64,linux/arm64
                cache-from: type=gha
                cache-to: type=gha,mode=max
  
    
                


